# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ActivityIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ActivityIOS
  pod 'mailcore2-ios'

  target 'ActivityIOS-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-mail', :path => '../node_modules/react-native-mail'


  end

  target 'ActivityIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end